name: kagi_task
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.2
  dots_indicator: ^3.0.0
  transparent_image: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  riverpod_annotation: ^2.1.1
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.11
  flutter_riverpod: ^2.3.6
  webview_flutter: ^4.10.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/data/news.json
      - assets/images/kite.png